version: "3"

services:
  caddy:
    ports:
      - 8080:8080
      - 8081:8081
    volumes:
      - ./.config/Caddyfile:/etc/caddy/Caddyfile

  vue:
    build: ./Front-End
    volumes:
      - ./Front-End:/app
      - /app/node_modules/

  web:
    build:
      dockerfile: Dockerfile
    volumes:
      - ./Back-End:/app

  sandbox:
    volumes:
      - ./Sandbox:/app

